#!/bin/sh

# 解决开启sing-box fakeip后触发dnsmasq DNS-rebind 警告，possible DNS-rebind attack detected

uci set dhcp.@dnsmasq[0].rebind_protection='0'
uci set dhcp.@dnsmasq[0].rebind_localhost='1'
uci commit dhcp

exit 0