#!/bin/sh


lan_ip="192.168.30.1/24"

# =========================
# 网络 IP 配置
# =========================
if [ -n "$lan_ip" ]; then
    uci set network.lan.ipaddr="$lan_ip"
    uci -q delete network.lan.netmask
fi

uci commit network

exit 0